### PR TITLE
New L1Trigger/DTTriggerPhase2 Files

### PR DESCRIPTION
**Pull request by jaimeleonh**
Adding new files for the DT Phase2 TPs:
  - Theta TP shifts
  - Local to global coordinates transformation
  - New patterns for the PseudoBayes grouping method

### CODE REVIEW

**Comment by srimanob** [comment]
Please test

**Comment by smuzaffar** [comment]
@jaimeleonh  , these are all new files, So I guess there is nothing in existing cmssw code to use/test ... right? Do you have any cmssw PR to use these new data files?

**Comment by jaimeleonh** [comment]
@smuzaffar We opened this PR to cmssw this morning https://github.com/cms-sw/cmssw/pull/33243

**Comment by smuzaffar** [comment]
thanks @jaimeleonh . By the way, I do not see any direct ref to these `createdPatterns*.root` files in cms-sw/cmssw#33243 , so are these newly added  `createdPatterns*.root` files really needed ?

**Comment by jaimeleonh** [comment]
@smuzaffar I think they will be used in a later PR to cmssw. @folguera can you confirm?

Edit: maybe they can be used instead of the file in this line: https://github.com/dtp2-tpg-am/cmssw/blob/AM_11_3_X_Integration/L1Trigger/DTTriggerPhase2/python/PseudoBayesGrouping_cfi.py#L3

**Comment by folguera** [comment]
indeed @smuzaffar they will be useed in a soon-to-come PR

**Comment by jaimeleonh** [comment]
Hi @smuzaffar , could you have a look at this failed check? Is there anything we need to do from our side? Thanks!

**Comment by smuzaffar** [comment]
please test
lets re-tests it based on latest IBs where newer clhep and related code has been integrated

**Comment by folguera** [comment]
Hi @smuzaffar is there anything else pending, can this be merged? The PR that needs these files has already been merged centrally: cms-sw/cmssw#33243

**Comment by smuzaffar** [comment]
+externals
@folguera it neds signatures from `l1` and `upgrade` . You also mentioned that there will a new cmssw PR which will use these new files? Is that PR already available?

**Comment by folguera** [comment]
@smuzaffar some of the files can be already used by the exising (and merged) PR (cms-sw/cmssw#33243) other files will be used by a future PR that still needs to be made. 

@rekovic, @cecilecaillol can you have a look at this?

**Comment by cecilecaillol** [comment]
+l1

**Comment by folguera** [comment]
Hi @smuzaffar we are still missing some signatures, who else should we ping to merge this?

**Comment by mrodozov** [comment]
@folguera this is only new files, correct ?

**Comment by folguera** [comment]
yes, only new files.

**Comment by mrodozov** [comment]
usually we don't merge data PRs if they are only new files not used by any code yet
I'll include the files in this night IB trough cms-sw/cmsdist#6903 , but if there is nothing in the release that is using the files - they are not needed in the release :)

**Comment by folguera** [comment]
sorry I dind't expressed clearly, all of the files are used by some code already merged in CMSSW, however only a subset of these files are used by the default version of the phase-2 DT trigger primitive generation code. The others are used by extensions that we are working on and optimizing, but a v0 of them is already in CMSSW.  All the files are new, they are not a modification of pre-existing files in this repo.

**Pull request merged**
