### PR TITLE
Add new LUTs for AMv2

### PR DESCRIPTION
**Pull request by jfernan2**

### CODE REVIEW

**Comment by jfernan2** [comment]
Needed for https://github.com/cms-l1t-offline/cmssw/pull/1166

**Comment by aloeliger** [comment]
please test

**Comment by rappoccio** [comment]
+1

**Comment by rappoccio** [comment]
merge

* PR is already signed for cmssw, this needs to go together with https://github.com/cms-sw/cmssw/pull/43390

**Comment by smuzaffar** [comment]
@rappoccio , once you merge a cms-data PR then bot will automatically open a cmsdist PR ( e.g in this case https://github.com/cms-sw/cmsdist/pull/8872 ). You need to merge that cmsdist PR otherwise new data files will be missing in IBs and can fail the tests if cmssw PR was requiring those data files. Anyway, I have merged https://github.com/cms-sw/cmsdist/pull/8872 now

**Pull request merged**
